# Generated by Django 4.2.3 on 2023-07-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_chois_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_date',
            new_name='question_text',
        ),
    ]
