# Generated by Django 4.2.3 on 2023-08-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_comments_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
