# Generated by Django 4.2.6 on 2023-10-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
